<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('ecocash_transactions', function (Blueprint $table): void {
            $table->id();
            $table->foreignId('team_id')->constrained()->cascadeOnDelete();
            $table->foreignId('invoice_id')->constrained()->cascadeOnDelete();

            /** Unique per-request ID generated by us and echoed back by EcoCash. */
            $table->string('client_correlator')->unique();

            /** Reference code we embed in the request; used to look up the transaction. */
            $table->string('reference_code')->unique();

            /** EcoCash number that was charged (e.g. 0777123456). */
            $table->string('phone_number', 20);

            /** Amount charged in the local currency (e.g. ZWG). */
            $table->decimal('local_amount', 15, 2);

            $table->string('local_currency', 10)->default('ZWG');

            $table->string('status', 30)->default('pending');

            /** Full JSON body returned by EcoCash on the initial request and/or notify callback. */
            $table->json('ecocash_response')->nullable();

            /** Set when EcoCash sends a "Charged" notification and the payment is recorded. */
            $table->foreignId('payment_id')->nullable()->constrained()->nullOnDelete();
            $table->timestamp('completed_at')->nullable();

            $table->timestamps();

            $table->index(['team_id', 'status']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('ecocash_transactions');
    }
};
